Fixes broken installation (#4)
* Made more verbose instructions and changed some things in the Procfile to see if that will fix the build issues

* pip addition?

* Add logging to start_jupyter

* hobby-dev is no longer a supported DB, changing

* Adding pip as an addl dependency to the yml files, also upgrading to essential-1 instead of a plan that no longer exists

* timeout?

* heroku timeout and auto dyno creation

* package versions in env.yaml were super old, updating to see if things can build now

* jupyter_contrib_nbextensions clone from ssh to https

* downgrading notebook to hopefully work with pgcontents

* python 3.9

* notebook 5.*, although pgcontents I think needs to update its code to work with the newer notebook package

* packages size test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* test

* no conda

* no conda

* no conda

* updates

* updates

* updates

* updates

* updates

* updates

* updates

* updates

* updates

* commentary on notebook start command

* removed yml files

* default bash shell

* prettier

* readme updates

* whitespace

* temp test

* test removal

* whitespace

* app.json change

* github install of pgcontents

* package versions

* updated readme

* readme update, not done yet

* README updates

* README updates

* Apt buildpack test

* README fix

diff --git a/start_jupyter b/start_jupyter
--- a/start_jupyter
+++ b/start_jupyter
@@ -1,11 +1,41 @@
 #!/usr/bin/env bash
 
-pgcontents init -l $DATABASE_URL --no-prompt
+# Update Conda environment with runtime dependencies
+# echo "Updating Conda environment..."
+# conda env update --file runtime.yml || { echo "Conda env update failed"; exit 1; }
 
+# # Install additional runtime pip dependencies
+# echo "Installing pip dependencies..."
+# pip install -r requirements.txt
+# pip install jupyter
+
+echo "Starting pgcontents initialization"
+echo "DATABASE_URL is $DATABASE_URL"
+pgcontents init --no-prompt -l $DATABASE_URL || exit 1
+# currently facing a known issue: https://github.com/quantopian/pgcontents/issues/80
+# need to modify this file, lol: /app/.conda/lib/python3.8/site-packages/pgcontents/alembic/versions/2d46c89138b0_.py
+# or w/ pip: /app/.heroku/python/lib/python3.10/site-packages/pgcontents/alembic/versions/2d46c89138b0_.py
+# comment out the first block ^^
+
+echo "pgcontents initialized"
+
+echo "Installing Jupyter extensions"
 jupyter contrib nbextension install --user
-jupyter nbextensions_configurator enable --user
+echo "Extensions installed"
 
+echo "Enabling nbextensions configurator"
+jupyter nbextensions_configurator enable --user
+echo "Nbextensions configurator enabled"
+
+# heroku will override $PS1 when specified as a config var, so I'm setting it here to make the jupyter
+# terminal interface a little prettier:
+export PS1='\[\033[01;34m\]\w\[\033[00m\]\$'
+
+echo "Starting Jupyter Notebook"
+# NOTE: With allow_origin='*', anyone with the URL and password can potentially access your notebook,
+# so be careful w/ the URL and password. Don't put sensitive data up here.
 jupyter notebook \
-	--no-browser --no-mathjax --ip=* --port $PORT \
-	$JUPYTER_NOTEBOOK_ARGS \
-	notebooks
+    --no-browser --no-mathjax --ip=0.0.0.0 --port=$PORT \
+    --NotebookApp.allow_origin='*' --NotebookApp.allow_credentials=True \
+    $JUPYTER_NOTEBOOK_ARGS \
+    notebooks
